### ISSUE TITLE
Install CM

### ISSUE THREAD

**Issue by mihenn87** [mihenn87/SEBC_Sydney#3]

**Comment by mfernest** [comment]
`2_cm.md` - I expected to see the output of your `scm_prepare_database.sh` invocation.

**Comment by mfernest** [comment]
I came back to look again, and saw that like Sebastian you also submitted a command for `scm_prepare_database.sh` but omitted it's command output -- something we did not practice. I just find it odd that my instructions could be interpreted in such a way that leaving out information in this process was better than leaving it in.
